# Generated by Django 3.2.8 on 2022-03-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='updated',
        ),
        migrations.AddField(
            model_name='pdf',
            name='pdf',
            field=models.FileField(default=1, upload_to='static'),
            preserve_default=False,
        ),
    ]
