# Generated by Django 3.1.7 on 2022-03-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_pdf_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='name',
        ),
        migrations.AddField(
            model_name='pdf',
            name='course_title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
